import weather from'./img/weather-pic.png'
const Pdata = [
    // {
    //   id: 1,
    //   category: "HTML/CSS",
    //   image: "/images/responsive netflix-clone.png",
    //   title: "Responsive Netflix Clone",
    //   desc: "The project is built using HTML, CSS, and JavaScript.",
    //   demo: "https://responsive-netflix-clone.vercel.app/",
    //   github: "",
    // },
    // {
    //   id: 2,
    //   category: "HTML/CSS",
    //   image: "/images/multipage-responsive-facebook-clone.png",
    //   title: "Responsive Facebook Clone",
    //   desc: "The project is built using HTML, CSS, and JavaScript.",
    //   demo: "",
    //   github:
    //     "",
    // },
    // {
    //   id: 3,
    //   category: "HTML/CSS",
    //   image: "/images/responsive-nike-clone.png",
    //   title: "Responsive Nike Clone",
    //   desc: "The project is built using HTML, CSS, and JavaScript.",
    //   demo: "",
    //   github: "",
    // },
    {
      id: 4,
      category: "ReactJS",
      image: weather,
      title: "React Responsive Weather ForeCasting",
      desc: "The project is built using HTML, CSS, JavaScript, React 18, Bootstrap, Axios,visual crossing API and GitHub.",
      demo: "https://samanta580.github.io/weather/",
      github:
        "https://github.com/samanta580/weather",
    },
    {
      id: 5,
      category: "ReactJS",
      image: weather,
      title: "React Responsive Restaurant Website",
      desc: "The project is built using HTML, CSS, JavaScript, React 18, React Router, Styled Components, Vite and Vercel.",
      demo: "",
      github:
        "https://github.com/",
    },
    {
      id: 6,
      category: "ReactJS",
      image: weather,
      title: "React Responsive Sneakers Store",
      desc: "The project is built using HTML, CSS, SCSS, JavaScript, React 18, React Router, and Vercel.",
      demo: "",
      github:
        "https://github.com",
    },
    {
      id: 7,
      category: "ReactJS",
      image:weather,
      title: "NextJS Responsive User Dashboard",
      desc: "The project is built using HTML, Tailwind CSS, JavaScript, Next.js 13, React.js 18, Chart.js, and Vercel.",
      demo: "",
      github:
        "https://github.com",
    },
    {
      id: 8,
      category: "ReactJS",
      image: weather,
      title: "React Responsive Google Search Clone",
      desc: "The project is built using HTML, Tailwind CSS, JavaScript, React.js 18, React Router, Axios, and Vercel.",
      demo: "",
      github:
        "",
    },
    {
      id: 9,
      category: "ReactJS",
      image: weather,
      title: "React Responsive ---------",
      desc: "The project is built using HTML, Bootstrap CSS, JavaScript, React.js 18, React Router, and Vercel.",
      demo: "",
      github: "",
    },
    // {
    //   id: 10,
    //   category: "React Native",
    //   image: "/images/react-native-food-delivery-app.png",
    //   title: "React Native Food Delivery App",
    //   desc: "The project is built using Expo, React Native, and React Native Navigation.",
    //   demo: "",
    //   github: "",
    // },
    // {
    //   id: 11,
    //   category: "React Native",
    //   image: "/images/react-native-fitness-app.png",
    //   title: "React Native Fitness App",
    //   desc: "The project is built using Expo, React Native, and React Native Navigation.",
    //   demo: "",
    //   github: "",
    // },
    // {
    //   id: 12,
    //   category: "React Native",
    //   image: "/images/react-native-movie-app.png",
    //   title: "React Native Movie App",
    //   desc: "The project is built using Expo, React Native, React Native Navigation, NativeWind, Axios, and TMDB Movie API.",
    //   demo: ",
    //   github: "",
    // },
    // {
    //   id: 13,
    //   category: "React Native",
    //   image: "/images/react-native-weather-app.png",
    //   title: "React Native Weather App",
    //   desc: "The project is built using Expo, React Native Navigation, NativeWind, HeroIcons, and WeatherAPI.",
    //   demo: "",
    //   github: "",
    // },
    // {
    //   id: 14,
    //   category: "React Native",
    //   image: "/images/react-native-linkedIn-clone.png",
    //   title: "React Native LinkedIn Clone",
    //   desc: "The project is built using React Native Expo CLI, React Native Navigation and JavaScript.",
    //   demo: "",
    //   github: "",
    // },
  ];
  
  export default Pdata;
  